### ISSUE TITLE
Question about person Index

### ISSUE THREAD

**Issue by padmanabanSampath** [spencercarli/offline-redux-actions#1]
Hai Spencer , actually it was really great example, but i dont understand why we are using person_index?
Please Explain it

**Comment by spencercarli** [comment]
The person index is there so that we wouldn't keep fetching the same person over and over. Incrementing it means we'll get a new person as a response, better demonstrating that things are working.

**Comment by padmanabanSampath** [comment]
thankyou for your reply, actually i found that after i posted the issue , when reading the code deeply, and you are doing really great things, i have followed and get some important ideas for my apps from your course and your medium posts and your github repos. kudos to you man
